### ISSUE TITLE
Features and fixes meta-issue

### ISSUE THREAD

**Issue by wasnotrice** [robmarti/cap-bluetooth-low-energy-client#4]
Hi @robmarti, I used your library as a starting point for integrating BLE into a capacitor project, knowing that I would need to add iOS support. I discovered a few more things I need in my project, and have been adding them as needed in my own branch.

How do you feel about rolling these changes back into the main project? I'd open proper PRs for each, if it makes sense. Otherwise, if not, I can just maintain a custom fork for my own purposes.

Here are the updates I've made (or am planning) on my fork:

- [x] support for iOS
- [x] support for custom service characteristics (32-bit strings) [web, android]
- [x] support for service filtering [android]
- [x] support for configurable scan timeout [android]
- [x] support for stopping scan after the first matching result [android]
- [x] fix for base64 data encoding (so that Android and web are compatible) [web]

Are these updates you would want to include?

**Comment by ghost** [comment]
Hi @wasnotrice ,
those are definitely changes I would include into the main project.
It would be awesome if you could create PRs for the new features/fixes.

**Comment by Kepro** [comment]
sorry, any ETA or smth for iOS support? :)

**Comment by wasnotrice** [comment]
I do have iOS support working on a fork. I made a lot of changes that were intertwined, as I was making sure the library could do everything I needed it to do. I will try to detangle the changes and make PRs one-at-a-time :)

**Comment by Kepro** [comment]
@wasnotrice maybe release it as "alpha" version? to help with testing? :))

**Comment by wasnotrice** [comment]
@robmarti I've finally started breaking apart my promised changes :) I'm submitting a set of pull requests today that target web and android. There are also a couple more. Once all of these are resolved, I'll make a request that adds nearly full iOS support for the current feature set. I think descriptors are the only bit that isn't implemented yet.

The pull requests are logically separate, but they assume the changes from previous PRs exist.

#10, #11, #12, #13 

/cc @Kepro
